;; Autopair
(require 'autopair)
;; global-mode is not compatible with slime-mode
;; (autopair-global-mode)
(defun my-common-mode-auto-pair ()
  (interactive)  
  (make-local-variable 'skeleton-pair-alist)  
  (setq skeleton-pair-alist  '(  
                               (? ? _ "''")  
                               (? ? _ """")  
                               (? ?  _ "()")  
                               (? ?  _ "[]")  
                               (?{ \n > _ \n ?} >)))  
  (setq skeleton-pair t)  
  (local-set-key (kbd "(") 'skeleton-pair-insert-maybe)  
  (local-set-key (kbd "\"") 'skeleton-pair-insert-maybe)  
  (local-set-key (kbd "{") 'skeleton-pair-insert-maybe)  
  (local-set-key (kbd "\'") 'skeleton-pair-insert-maybe)  
  (local-set-key (kbd "[") 'skeleton-pair-insert-maybe))  
(add-hook 'c-mode-hook 'my-common-mode-auto-pair)  
(add-hook 'c++-mode-hook 'my-common-mode-auto-pair)  
(add-hook 'java-mode-hook 'my-common-mode-auto-pair)  
(add-hook 'lisp-mode-hook 'my-common-mode-auto-pair)  
(add-hook 'web-mode-hook 'my-common-mode-auto-pair)
(add-hook 'js2-mode-hook 'my-common-mode-auto-pair)  
(add-hook 'python-mode-hook 'my-common-mode-auto-pair)  
(add-hook 'html-mode-hook 'my-common-mode-auto-pair)  
(add-hook 'scheme-mode-hook 'my-common-mode-auto-pair)  
(add-hook 'css-mode-hook 'my-common-mode-auto-pair)  
(add-hook 'sql-mode-hook 'my-common-mode-auto-pair)  
(add-hook 'emacs-lisp-mode-hook 'my-common-mode-auto-pair)  
(add-hook 'text-mode-hook 'my-common-mode-auto-pair)  
(add-hook 'slime-repl-mode-hook 'my-common-mode-auto-pair)  
